kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jmeter-operator
subjects:
- kind: ServiceAccount
  name: jmeter-operator
  namespace: jmeter
roleRef:
  kind: ClusterRole
  name: jmeter-operator
  apiGroup: rbac.authorization.k8s.io
